service: serverless-app-info-scraper

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  timeout: 12

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  getAppInfoByIdFromGooglePlay:
    handler: src/googleplay.handler
    events:
      - http:
          path: googleplay
          method: get
          cors: true
  getAppInfoByIdFromAppStore:
    handler: src/appstore.handler
    events:
      - http:
          path: appstore
          method: get
          cors: true
  searchAppIdsByKeyword:
    handler: src/searchAppIds.handler
    events:
      - http:
          path: app-search
          method: get
          cors: true
